apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 80  # The port exposed by the service within the cluster
      targetPort: 8080  # The port your React app is listening on inside the pod
  type: NodePort
