name: Build and Deploy to Remote EC2 Tomcat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t mobinbhojani/tomcatstar:latest .

      - name: Publish image to Docker Hub
        run: docker push mobinbhojani/tomcatstar:latest
  deploy:
    runs-on: self-hosted	
    needs: build

    steps:
      - name: Deploy Docker Image to Remote EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@13.201.100.44 << 'EOF'
            docker pull mobinbhojani/tomcatstar:latest
            
            # Stop and remove any existing container (optional)
            docker rm -f tomcatstar || true
            
            # Run the new container
            docker run -d --name tomcatstar -p 8080:8080 mobinbhojani/tomcatstar:latest
          EOF

