name: Build and Deploy to Remote EC2 Tomcat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build WAR with Maven
        run: mvn clean package

      - name: Copy WAR to Remote EC2 via SCP
        run: |
          REMOTE_USER=ubuntu
          REMOTE_HOST=13.201.100.44
          TEMP_PATH=/home/ubuntu/app.war

          WAR_PATH=$(ls webapp/target/*.war | head -n1)
          echo "WAR found at $WAR_PATH"

          echo "Copying WAR to remote EC2..."
          scp -i ~/.ssh/id_ed25519 "$WAR_PATH" "$REMOTE_USER@$REMOTE_HOST:$TEMP_PATH"

      - name: Move WAR and Restart Tomcat
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@13.201.100.44 << 'EOF'
          sudo mv /home/ubuntu/app.war /opt/tomcat11/webapps/app.war
          sudo systemctl restart tomcat
          EOF

